### ISSUE TITLE
express is undefined 

### ISSUE THREAD

**Issue by ccfiel** [rzvdaniel/moleculer-firebase-tutorial#5]
I tried clone and deploy the app in firebase I got this error

```
chris@chris-zenBook:~/moleculer-firebase-tutorial$ firebase deploy
⚠  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.

=== Deploying to 'kahero-api'...

i  deploying functions, hosting
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'express' of undefined
    at Object.<anonymous> (/home/chris/moleculer-firebase-tutorial/functions/server.js:14:46)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/chris/moleculer-firebase-tutorial/functions/index.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

Any ideas? :)

**Comment by ccfiel** [comment]
I have solve it just run ```firebase deploy``` inside  function folder :) thanks for the great blog
